[tool.poetry]
name = "crypto-react"
version = "0.1.0"
description = ""
authors = ["kargarisaac <kargarisaac@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mcpdoc = "^0.0.7"
baml-py = "^0.81.3"
duckduckgo-search = "^7.5.5"
requests = "^2.32.3"
langgraph = "^0.3.21"
langchain-community = "^0.3.20"
langgraph-cli = {extras = ["inmem"], version = "^0.1.81"}


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
