###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401,F821
# flake8: noqa: E501,F401,F821
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class Tool(str, Enum):
    
    WebSearch = "WebSearch"
    PriceLookup = "PriceLookup"

class Answer(BaseModel):
    cited_answer: str
    references: List["Source"]

class Clarification(BaseModel):
    needed: bool
    question: str

class ContextItem(BaseModel):
    content: str
    source: Optional[str] = None

class Critique(BaseModel):
    is_good: bool
    missing_info: str

class Plan(BaseModel):
    steps: List["Step"]

class RankedResultItem(BaseModel):
    content: Optional[str] = None
    link: Optional[str] = None
    relevance_score: int

class ResultItem(BaseModel):
    content: Optional[str] = None
    link: Optional[str] = None

class Source(BaseModel):
    index: int
    source: str
    source_type: str

class Step(BaseModel):
    tool: "Tool"
    query: str
